language: cpp
matrix:
  include:
    - env: toolset=gcc
    - os: osx
      osx_image: xcode8
      env: toolset=darwin

branches:
  only:
    - master

git:
  submodules: false
  depth: 1

addons:
  apt:
    sources:
    - boost-latest
    - ubuntu-toolchain-r-test
    packages:
    - libboost1.55-tools-dev
    - g++-5

install:

  - 'if [[ $TRAVIS_OS_NAME == "osx" ]]; then brew update > /dev/null && brew install --quiet boost-build; fi'
  - touch ~/user-config.jam
  - 'if [[ $toolset == "gcc" ]]; then
      g++-5 --version;
      echo "using gcc : : g++-5 : <cxxflags>-std=c++11 ;" >> ~/user-config.jam;
    fi'
  - 'echo "using darwin : : clang++ : <cxxflags>-std=c++11 ;" >> ~/user-config.jam'

script:

  - bjam link=static stage_test
  - ./bin/test

